# Generated by Django 3.2.16 on 2022-10-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='featured_image',
        ),
    ]
