# Generated by Django 3.2.16 on 2022-10-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20221027_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date_time']},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date_time_start',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
