# Generated by Django 3.2.16 on 2022-10-30 16:26

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_auto_20221030_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_time',
            field=models.DateTimeField(null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 10, 30, 16, 26, 14, 422487, tzinfo=utc), 'Please pick a date and time before present time')]),
        ),
    ]
