# Generated by Django 3.2.16 on 2022-10-31 18:28

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_alter_reservation_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_time',
            field=models.DateTimeField(null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 10, 31, 18, 28, 41, 705919, tzinfo=utc), 'Please pick a date\n                                                  and time\n                                                  before present time')]),
        ),
    ]
