# Generated by Django 3.2.16 on 2022-10-31 18:59

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_alter_reservation_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_time',
            field=models.DateTimeField(null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 10, 31, 18, 59, 41, 393291, tzinfo=utc), 'Please pick a date\n                                                  and time\n                                                  before present time')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not approved'), (1, 'Approved')], default=0),
        ),
    ]
